# Generated by Django 5.2 on 2025-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_remove_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/avatar-gender.webp', upload_to='profile_pics/'),
        ),
    ]
