# Generated by Django 5.2 on 2025-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='product/avatar-gender.webp', upload_to='profile_pics/'),
        ),
    ]
