# Generated by Django 5.2 on 2025-05-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_alter_category_id_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default.webp', upload_to='profile_images/'),
        ),
    ]
