# Generated by Django 5.2 on 2025-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_remove_product_sold_to_product_sold_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='payment',
            name='dispatch_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='location',
            field=models.CharField(default='Default Location', max_length=255),
            preserve_default=False,
        ),
    ]
