# Generated by Django 5.2 on 2025-05-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_rename_created_at_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sold',
            new_name='is_sold',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
